<style>
    table{
        border:3px dashed blue;
    }

    .cell{
        border:2px solid green;
    }
</style>
bdfdgfdgfdg
<table>
    <?php

            if(isset($this->test)){
                foreach($this->test as $testUser){
                    ?>
                    <tr class="row"><td class="cell"><?php echo $testUser->getId(); ?></td><td class="cell"><?php echo $testUser->getFirstname(); ?></td></tr>
            <?php
                }
            }


    ?>

</table>

