<style>
    table{
        border:3px dashed blue;
    }

    .cell{
        border:2px solid green;
    }
</style>
<?php echo '<pre>';var_dump($this->test); ?>
<table>
    <?php

            if(isset($this->studenti)){
                foreach($this->studenti as $student){
                    ?>
                    <tr class="row"><td class="cell"><?php echo $student['nume']; ?></td><td class="cell"><?php echo $student['varsta']; ?></td></tr>
            <?php
                }
            }


    ?>

</table>

