<?php $this->headLink()->appendStylesheet('/media/css/navbar.css') ?>
<?= $this->cssHelper() ?>
<?php $this->headScript()->appendFile('/media/js/jQuery.js') ?>
<?php $this->headScript()->appendFile('/media/js/underscore.js') ?>
<?php $this->headScript()->appendFile('/media/js/backbone.js') ?>
<?php $this->headScript()->appendFile('/media/js/navbar/navbar.js') ?>
<?= $this->headScript() ?>

<?php
echo $this->render('partials/navbar.phtml'); ?>
















<script>
  var view = new testView();
</script>





